FROM apache/airflow:2.8.1-python3.10

USER airflow

COPY requirements.airflow.txt .
RUN pip install torch==2.2.1 --index-url https://download.pytorch.org/whl/cpu && \
    pip install --no-cache-dir -r requirements.airflow.txt