version: "3.8"

services:

  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__FERNET_KEY: "ovh2_0912iotvg6_f-i4KIUqmGa5sQ-LjS-0RPIHSeE="
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    volumes:
      - airflow_db:/opt/airflow/db
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin \
        --firstname Admin --lastname User \
        --role Admin --email admin@example.com || true &&
      exec airflow webserver
      "

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__FERNET_KEY: "ovh2_0912iotvg6_f-i4KIUqmGa5sQ-LjS-0RPIHSeE="
    volumes:
      - airflow_db:/opt/airflow/db
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: scheduler
    depends_on:
      - airflow-webserver

  qna-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llm-qa-app
    ports:
      - "8000:8000"
    volumes:
      - ./mlruns:/app/mlruns
      - ./data:/app/data 
    depends_on:
      - airflow-scheduler

  mlflow-ui:
    image: ghcr.io/mlflow/mlflow:v2.10.1
    container_name: mlflow-ui
    ports:
      - "5050:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --backend-store-uri /mlflow/mlruns --host 0.0.0.0 --port 5000

volumes:
  airflow_db: